module.exports = {
    clientId: "657310407786233875",
    embedOptions: {
        colors: {
            success: 2336090,
            party: 13699564,
            warning: 15774258,
            error: 15875907,
            info: 5793266,
            note: 8422542
        },
        icons: {
            logo: '🤖',
            beta: '`beta`',
            new: '`new`',
            rule: '📒',
            support: '❓',
            bot: '🤖',
            server: '🖥️',
            discord: '🌐',
            audioPlaying: '🎶',
            audioStartedPlaying: '🎶',
            success: '✅',
            error: '⚠️',
            warning: '⚠️',
            disable: '🚫',
            enable: '✅',
            disabled: '✅',
            enabled: '✅',
            nextTrack: '⏭️',
            previousTrack: '⏮️',
            pauseResumeTrack: '⏯️',
            shuffleQueue: '🔀',
            loop: '🔁',
            loopAction: '🔁',
            autoplay: '♾️',
            autoplayAction: '♾️',
            looping: '🔁',
            autoplaying: '♾️',
            skipped: '⏭️',
            back: '⏮️',
            pauseResumed: '⏯️',
            shuffled: '🔀',
            volume: '🔊',
            volumeIsMuted: '🔇',
            volumeChanged: '🔊',
            volumeMuted: '🔇',
            queue: '🎶',
            sourceArbitrary: '🎵',
            sourceAppleMusic: '🎵',
            sourceYouTube: '🎵',
            sourceSoundCloud: '🎵',
            sourceSpotify: '🎵',
            party: "🎉"
        }
    }
}